### ISSUE TITLE
LilyGO 1.14" display

### ISSUE THREAD

**Issue by Ralph-Rastaetter** [russhughes/st7789py_mpy#5]
Hi Russ,
I have a LilyGo RP2040 with a 1.14" LCD display. I downloaded the st7789py.zip file, copied all the directories except for the doc directory to the LilyGO, and none of the applications that use text will run. :( 
I am running Thonny as the editor, and am using the most current versions of all the applications.
From the Examples directory, both feathers.py, and lines.py run fine.
![LilGO_Picture](https://user-images.githubusercontent.com/103387274/162640986-562ebcd5-41b4-4d30-a0c9-e7c8c9df9a36.jpg)

However, all the text display examples provide pretty much the same complaint.
Basically they all through the same error about no module named romfonts.

The fonts.py application returns the following error:
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
ImportError: no module named 'romfonts'
16 from romfonts import vga2_8x8 as font1

The hello.py application returns the following error:
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
ImportError: no module named 'romfonts'
27 from romfonts import vga2_bold_16x32 as font

The scroll.py application returns the following error:
Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
ImportError: no module named 'romfonts
23 from romfonts import vga2_bold_16x16 as font

Therefore my question is, what am I doing wrong?
Thank You,
Ralph Rastaetter
zweisteine.1@gmail.com

**Comment by Ralph-Rastaetter** [comment]
Hi Russ,
I solved the issue.
The directory structure on the LilyGO RP2040 1.14"(st7789)needs to be adjusted to:
examples
lib
romfonts
sphinx
truetype
utils

In effect the fonts directory needs to be removed from the "Tree", and the contents of the fonts directory(romfonts, and truetype) both need to be placed under the root directory for the example programs to actually run.

Thank You,
Ralph
